# ============================================================================
#  gen_assets.ps1
#
#  Scans assets\ and regenerates two files next to this project:
#
#    Ransom_dev\assets_gen.rc    every asset as an RCDATA resource with a
#                                numeric id (1001, 1002, ...), plus one extra
#                                resource (id 1000) holding the manifest below
#    Ransom_dev\assets_gen.txt   the manifest: one "<KIND>\t<name>\t<id>" line
#                                per asset
#
#  The runtime (src\assets.cpp) reads resource 1000 once, builds a
#  name -> id table and then pulls bytes with FindResourceW. Why a manifest
#  instead of encoding the file name into the resource name: rc.exe keeps the
#  double quotes of a quoted resource name as part of the name, and bare RC
#  identifiers cannot contain '-', '.', '(' or ')'. Real file names can, so the
#  mapping is data, not an identifier.
#
#  A normal build runs this on every build (the GenerateAssetResources target has
#  no Inputs/Outputs), but writing only happens when the CONTENT changed. That is
#  deliberate: MSBuild's incremental check compares timestamps, and a new asset
#  can arrive with an old timestamp (Copy-Item / unzip both preserve it), which
#  makes a timestamp-only check silently skip the new file. Comparing content is
#  correct in every case, and "no write" means the .rc keeps its timestamp, so
#  rc.exe and the linker stay idle and the build does not get slower.
#
#  NOTE: this file is deliberately ASCII-only. PowerShell 5.1 reads .ps1 files
#  using the machine ANSI code page (GBK here), so CJK text in the script body
#  turns into mojibake and can even swallow the closing quote of a string.
#  The readable Chinese explanation lives in Ransom_dev.rc instead.
# ============================================================================
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot          # tools\ -> repo root
$assetDir = Join-Path $repoRoot 'assets'
$outRc    = Join-Path $repoRoot 'Ransom_dev\assets_gen.rc'
$outTxt   = Join-Path $repoRoot 'Ransom_dev\assets_gen.txt'

if (-not (Test-Path -LiteralPath $assetDir)) {
    throw "asset directory not found: $assetDir"
}

$manifestId      = 1000
$nextId          = 1001

# kind tag -> sub directory ('' means assets\ itself)
$groups = @(
    @{ Tag = 'ROOT'; Sub = '' },
    @{ Tag = 'IMG';  Sub = 'image' },
    @{ Tag = 'AUD';  Sub = 'audio' }
)

$rc   = New-Object System.Collections.Generic.List[string]
$mani = New-Object System.Collections.Generic.List[string]

[void]$rc.Add('// Generated by tools\gen_assets.ps1 -- DO NOT EDIT BY HAND.')
[void]$rc.Add('// Regenerate:  powershell -ExecutionPolicy Bypass -File tools\gen_assets.ps1')
[void]$rc.Add('// (a normal build does this automatically when assets\ changes)')
[void]$rc.Add('//')
[void]$rc.Add('// Paths use forward slashes on purpose: rc.exe processes \a \r \n ... as')
[void]$rc.Add('// escape sequences inside quoted strings, so "..\assets\x.png" would')
[void]$rc.Add('// silently look for "..<BELL>ssets\x.png".')
[void]$rc.Add('')
[void]$rc.Add("// manifest: one `"<KIND>`t<name>`t<id>`" line per asset")
[void]$rc.Add("$manifestId RCDATA `"assets_gen.txt`"")
[void]$rc.Add('')

$total = 0
$totalBytes = 0
$seen = @{}

foreach ($g in $groups) {
    $sub = $g.Sub
    $dir = if ($sub -eq '') { $assetDir } else { Join-Path $assetDir $sub }
    if (-not (Test-Path -LiteralPath $dir)) { continue }

    # flat listing on purpose: the asset folders have no nesting
    $files = @(Get-ChildItem -LiteralPath $dir -File -Force | Sort-Object Name)
    if ($files.Count -eq 0) { continue }

    $relDir = if ($sub -eq '') { '' } else { "$sub/" }
    [void]$rc.Add("// ---- assets/$relDir ----")

    foreach ($f in $files) {
        $key = "$($g.Tag)/$($f.Name)"
        if ($seen.ContainsKey($key)) { throw "duplicate asset key: $key" }
        $seen[$key] = $true

        $id = $nextId
        $nextId++

        [void]$rc.Add(('{0} RCDATA "../assets/{1}{2}"' -f $id, $relDir, $f.Name))
        # real TABs, not the literal two characters -- single quotes do not
        # expand `t in PowerShell
        [void]$mani.Add(('{0}{1}{2}{1}{3}' -f $g.Tag, [char]9, $f.Name, $id))

        $total++
        $totalBytes += $f.Length
    }
    [void]$rc.Add('')
}

[void]$rc.Add("// $total resources, $totalBytes bytes")

function Write-IfChanged([string]$path, $lines) {
    $enc  = New-Object System.Text.UTF8Encoding $false
    $newT = ($lines -join "`r`n") + "`r`n"
    if (Test-Path -LiteralPath $path) {
        $oldT = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
        if ($oldT -eq $newT) { return $false }
    }
    [System.IO.File]::WriteAllText($path, $newT, $enc)
    return $true
}

# The project references assets_gen.rc from Ransom_dev.rc, not the manifest, so
# a manifest-only change would still need rc.exe to re-run. Touching the .rc when
# the manifest changed keeps the two in lockstep.
$rcChanged  = Write-IfChanged $outRc  $rc
$txtChanged = Write-IfChanged $outTxt $mani
if ($txtChanged -and -not $rcChanged) { (Get-Item $outRc).LastWriteTime = Get-Date }

Write-Output ("gen_assets: {0} resources, {1:N0} bytes (manifest id {2}, ids 1001..{3}) -- {4}" -f `
    $total, $totalBytes, $manifestId, ($nextId - 1),
    $(if ($rcChanged -or $txtChanged) { 'updated' } else { 'unchanged' }))
